name: Deploy to AWS EC2 with Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build and Run Docker Container
        run: |
          docker stop my-app || true
          docker rm my-app || true
          docker build -t my-app .
          docker run -d --name my-app -p 80:3000 my-app
