name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted # Using your EC2 as a self-hosted runner

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build -t my-html-app .

      - name: Stop and Remove Old Container
        run: |
          docker stop my-html-container || true
          docker rm my-html-container || true
          # Kill any process using port 80
          sudo fuser -k 80/tcp || true

      - name: Run New Container
        run: docker run -d -p 80:80 --name my-html-container my-html-app
