name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: self-hosted # Run tests on EC2

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          cd ~/your-project-folder
          npm install  # For Node.js
          # pip3 install -r requirements.txt  # Uncomment for Python
          # mvn clean install  # Uncomment for Java

      - name: Run Unit Tests
        run: |
          cd ~/your-project-folder
          npm test  # Replace with pytest for Python or mvn test for Java

      - name: Run Integration Tests
        run: |
          cd ~/your-project-folder
          npm run test:integration  # Modify based on your framework

  deploy:
    runs-on: self-hosted
    needs: test  # Ensure tests pass before deployment

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build -t my-html-app .

      - name: Stop and Remove Old Container
        run: |
          docker stop my-html-container || true
          docker rm my-html-container || true

      - name: Run New Container
        run: docker run -d -p 80:80 --name my-html-container my-html-app
