- name: Build and Run Docker Container
  run: |
    echo "Deploying Docker container on EC2 instance..."
    
    cd /home/ubuntu/actions-runner/_work/SE/SE || exit 1

    docker stop my-app || true
    docker rm my-app || true

    # Ensure Dockerfile exists before building
    if [ ! -f Dockerfile ]; then
      echo "Error: Dockerfile not found!"
      exit 1
    fi

    docker build -t my-app .
    docker run -d --name my-app -p 80:80 my-app
