name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          cd ~/actions-runner/_work/SE
          npm install  # Change to pip install -r requirements.txt if using Python
          # or mvn clean install if using Java

      - name: Run Unit Tests
        run: |
          cd ~/actions-runner/_work/SE
          npm test  # Change to pytest if using Python
          # or mvn test if using Java

  deploy:
    needs: test  # Runs only if the test job succeeds
    runs-on: self-hosted  

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Move to Project Directory
        run: cd ~/actions-runner/_work/SE

      - name: Build Docker Image
        run: docker build -t my-html-app ~/actions-runner/_work/SE

      - name: Stop and Remove Old Container
        run: |
          docker stop my-html-container || true
          docker rm my-html-container || true

      - name: Run New Container
        run: docker run -d -p 80:80 --name my-html-container my-html-app
